### ISSUE TITLE
code written purely in Python

### ISSUE THREAD

**Issue by trevoravant** [arobey1/LipSDP#3]
I'd just like to note that I have forked this project to run purely in Python (i.e. no Matlab). I think it may be helpful for those who don't want to install Matlab or don't have a license:

https://github.com/trevoravant/LipSDP_python

**Comment by arobey1** [comment]
Yeah this looks great.  There are issues with scaling SDPs in cvxpy, which is why we chose to stick with CVX and MATLAB.  But for smaller networks this should work nicely.

**Comment by trevoravant** [comment]
Oh gotcha, thanks for the info. Yeah I was able to reproduce all of the results from the examples shown in the README, but I had to play around with cvxpy's solvers (e.g. MOSEK, CVXOPT). For some of the examples, Mosek would give me "Out of space" errors, but those seemed to be fixed by changing the solver to CVXOPT. But I haven't experimented with larger networks.

**Comment by arobey1** [comment]
Yeah -- I found that cvxpy in general has memory leakage problems with SDPs.  I'm glad switching the solver helped.  I would guess that larger networks will present more of a problem, but would be glad to be proved wrong.

**Comment by sarosijbose** [comment]
Hi @trevoravant, did you implement LipSDP for a single layer neural network in your fork?

**Comment by trevoravant** [comment]
Hi @sarobml2000, I tried to keep my fork as close as possible to the original repo. So I think my fork should work the same as LipSDP for a single layer. I made an issue about running LIpSDP on a single layer [here](https://github.com/arobey1/LipSDP/issues/4).

But I *think* you can run LipSDP on a single layer as follows. Considering a 2x10 random weight matrix as an example, first create the `.mat` file (adapted from the README):
```python
import numpy as np
from scipy.io import savemat
import os

net_dims = [2, 10, 10] 
fname = os.path.join(os.getcwd(), 'saved_weights/random_weights.mat')
weight_list = [np.random.rand(net_dims[1], net_dims[0]), np.eye(net_dims[1])]
arr = np.empty(2, dtype=object)
arr[:] = weight_list
data = {'weights': arr}
savemat(fname, data)
```
Then run (from the README):
```
python solve_sdp.py --form neuron --weight-path examples/saved_weights/random_weights.mat
```

Furthermore, I believe implementing LipSDP on a single layer will just return the spectral norm of the weight matrix. This is what I observed, but I'm not an author of LipSDP and am not an expert on the math.

**Comment by sarosijbose** [comment]
Hi @trevoravant, thanks a lot for your reply. Sorry for taking about this here though maybe you could enable issues in your fork.

**Comment by trevoravant** [comment]
@sarobml2000 Sorry but I probably won't as I'm not an author of LipSDP, so I'm not comfortable adding any new that's mathematical in nature. I was comfortable converting LipSDP to Python because that basically just involved converting Matlab functions to Python functions. My intention was to mirror the original LipSDP repo as close as possible.
